### ISSUE TITLE
Language dependancies within Names

### ISSUE THREAD

**Issue by maninweb** [MartinTrummer/excel-names#3]
Hi Martin,

first, awesome project :-)

I found this link through an article from Debra Dalgleish's blog [Contextures](http://blog.contextures.com/archives/2017/12/07/what-are-the-rules-for-excel-names/), where she mentionned you.

If I have not overseen something in your code/validations, then I have a additional note regarding names: they are also language dependant. For example, in a German Excel version. the name "L" is allowed. However, if you switch to Excel in French, "L" is not allowed. The effect is then, that if you use "L" in a German file and a french user with a french Excel version opens it, then Excel repairs the file and removes the invalid name. This as the R1C1 style is L1C1 in french. Another sample is e.g. "Z1R2" which is allowed in Excel french but not in German.

Best,
Mourad

**Comment by MartinTrummer** [comment]
Thanks for the info.  
I've updated the [cell-references section](https://github.com/MartinTrummer/excel-names/blob/master/VbaCode.md#cell-references) and added a note to the main readme file.

**Comment by maninweb** [comment]
Thanks Martin :-)
